#!/bin/bash
echo Please build the class with gradle build or with the ide plugin
echo To get reloaded
echo JAVA_OPTS=$JAVA_OPTS
#gradle $@ bootRun
java $JAVA_OPTS -jar  build/libs/micro-service1.jar

